MangaHub/Models/Chapter.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MangaHub.Models
{
    public class Chapter
    {
        public Manga Manga { get; set; }
        [Key, Column(Order =1)]
        public int MangaId { get; set; }
        [Key, Column(Order =0)]
        public int ChapterNo { get; set; }
        public int NumberOfPages { get; set; }
        public string Information { get; set; }
        public DateTime DateTime { get; set; }
    }
}

MangaHub/Controllers/Api/ChaptersController.cs
using AutoMapper;
using MangaHub.Core;
using MangaHub.Core.Dtos;
using MangaHub.Core.Models;
using MangaHub.Utility;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Http;

namespace MangaHub.Controllers.Api
{
    public class ChaptersController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public ChaptersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpPost, Authorize]
        public IHttpActionResult Add(ChapterDto dto)
        {
            
            if (!ModelState.IsValid)
            {
                var errorMessage = string.Join(" | ", ModelState.Values
                .SelectMany(v => v.Errors)
                .Select(e => e.ErrorMessage));
                return BadRequest();
            }

            if (dto is null)
                return BadRequest();

            var userId = User.Identity.GetUserId();

            var manga = _unitOfWork.MangaRepo.GetManga(dto.MangaId);

            if (manga == null)
                return NotFound();

            if (manga.ArtistId != userId)
                return Unauthorized();

            if (_unitOfWork.ChapterRepo.GetChapterForManga(dto.MangaId, dto.ChapterNo) != null)
                return BadRequest($"The Chapter {dto.ChapterNo} already exists for the specified Manga");

            var mangaChapter = Mapper.Map<ChapterDto, Chapter>(dto);

            _unitOfWork.ChapterRepo.Add(mangaChapter);
            _unitOfWork.Complete();

            return Ok();
        }

        [HttpDelete, Authorize]
        public IHttpActionResult RemoveChapterForManga(string key)
        {
            var chapterKeyArray = key.Split(Chapter.KeyCodeDelimiter);
            
            
            if(chapterKeyArray.Length != 2 || 
                !int.TryParse(chapterKeyArray[0], out var mangaId) ||
                !int.TryParse(chapterKeyArray[1], out var chapterNo)
                )  
            {
                return BadRequest($"value for {nameof(key)} is not valid");
            }


            var userId = User.Identity.GetUserId();

            var manga = _unitOfWork.MangaRepo.GetManga(mangaId);

            if (manga == null)
                return NotFound();

            if (manga.ArtistId != userId)
                return Unauthorized();

            var chapter = _unitOfWork.ChapterRepo.GetChapterForMangaWithReaders(mangaId, chapterNo);

            if (chapter == null)
                return NotFound();

            var notifier = new Notifier();
            var notificationMessage = $"{manga.Artist.Name} removed Chapter {chapter.ChapterNo} for {manga.Title}";
            notifier.NotifyUpdate(manga.Readings.Select(r => r.User), notificationMessage);

            _unitOfWork.ChapterRepo.Remove(chapter);

            _unitOfWork.Complete();

            return Ok();

        }
    }
}

MangaHub/Controllers/ChaptersController.cs
using AutoMapper;
using MangaHub.Core;
using MangaHub.Core.Models;
using MangaHub.Core.ViewModels;
using MangaHub.Utility;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace MangaHub.Controllers
{
    public class ChaptersController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public ChaptersController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [Authorize]
        public ActionResult Create(int mangaId)
        {
            var manga = _unitOfWork.MangaRepo.GetManga(mangaId);
            if (manga == null)
                return HttpNotFound();

            var viewModel = new ChapterFormViewModel
            {
                MangaId = manga.Id,
                MangaPicture = manga.Picture,
                MangaTitle = manga.Title
            };

            return View("ChapterForm",viewModel);
        }

        [HttpPost]
        [Authorize]
        public ActionResult Create(ChapterFormViewModel viewModel)
        {
            if(!ModelState.IsValid)
            {
                return View("ChapterForm", viewModel);
            }

            var manga = _unitOfWork.MangaRepo.GetMangaWithReaders(viewModel.MangaId);
            if (manga == null)
                return HttpNotFound();

            var userId = User.Identity.GetUserId();

            if (manga.ArtistId != userId)
                return new HttpUnauthorizedResult();

            if (_unitOfWork.ChapterRepo.GetChapterForManga(viewModel.MangaId, viewModel.ChapterNo) != null)
            {
                ModelState.AddModelError("ChapterNo",
                    $"The Chapter {viewModel.ChapterNo} already exists for the specified Manga");
                return View("ChapterForm", viewModel);
            }

            var mangaChapter = Mapper.Map<ChapterFormViewModel, Chapter>(viewModel);
            mangaChapter.Manga = manga;

            var notifier = new Notifier();
            var notificationMessage = $"{manga.Artist.Name} added Chapter {mangaChapter.ChapterNo} for {manga.Title}";
            notifier.NotifyUpdate(manga.Readings.Select(r => r.User), notificationMessage);

            _unitOfWork.ChapterRepo.Add(mangaChapter);

            _unitOfWork.Complete();

            return RedirectToAction("Mine", "Mangas");
        }
    }
}

MangaHub/Views/Chapters/ChapterForm.cshtml
@model MangaHub.Core.ViewModels.ChapterFormViewModel
@{
    ViewBag.Title = "Add Chapter";
}

<h2>Add a Chapter</h2>


@using (Html.BeginForm("Create", "Chapters", FormMethod.Post, new { @class = "row" }))
{
    @Html.HiddenFor(m => m.MangaId)
    @Html.HiddenFor(m => m.MangaTitle)
    @Html.HiddenFor(m => m.MangaPicture)

    <div class="col-12 col-lg-12">
        <h2>@Model.MangaTitle</h2>
    </div>

    if (Model.MangaPicture != null && Model.MangaPicture.Length > 0)
    {
        <div class="col-12 col-lg-4">
            <div class="manga-picture">
                @{
                    var imageSrc = string.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(Model.MangaPicture));
                    <img src=@imageSrc />
                }
            </div>
        </div>
    }
    <div class="col-12 col-lg-8">
        <div class="form-group">
            @Html.LabelFor(m => m.Information)
            @Html.TextBoxFor(m => m.Information, new { @class = "form-control", autofocus="autofocus" })
            @Html.ValidationMessageFor(m => m.Information)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.ChapterNo)
            @Html.TextBoxFor(m => m.ChapterNo, new { @class = "form-control", type = "number", min="1", oninput="validity.valid;" })
            @Html.ValidationMessageFor(m => m.ChapterNo)
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.NumberOfPages)
            @Html.TextBoxFor(m => m.NumberOfPages, new { @class = "form-control", type = "number", min = "1", oninput = "validity.valid;"})
            @Html.ValidationMessageFor(m => m.NumberOfPages)
        </div>
        <button type="submit" class="btn btn-primary btn-lg">Add</button>
    </div>
}