MangaHub/Controllers/Api/MangasController.cs
using MangaHub.Core;
using MangaHub.Utility;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Http;

namespace MangaHub.Controllers.Api
{
    public class MangasController : ApiController
    {
        private readonly IUnitOfWork _unitOfWork;

        public MangasController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        [HttpDelete, Authorize]
        public IHttpActionResult Delete(int id)
        {
            var userId = User.Identity.GetUserId();

            var manga = _unitOfWork.MangaRepo.GetMangaWithReaders(id);

            if (manga == null)
                return NotFound();

            if (manga.ArtistId != userId)
                return Unauthorized();

            var notifier = new Notifier();
            var notificationMessage = $"{manga.Artist.Name} removed Manga: {manga.Title}";
            notifier.NotifyDelete(manga.Readings.Select(r => r.User), notificationMessage);

            _unitOfWork.MangaRepo.Remove(manga);

            _unitOfWork.Complete();

            return Ok(id);
        }
    }
}

MangaHub/Controllers/HomeController.cs
using MangaHub.Core;
using MangaHub.Core.ViewModels;
using Microsoft.AspNet.Identity;
using System.Linq;
using System.Web.Mvc;

namespace MangaHub.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public HomeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
            
        }
        public ViewResult Index(string id = null)
        {
            var viewModel = new MangasViewModel
            {
                Mangas = _unitOfWork.MangaRepo.GetMangasWithChapters(id)
            };

            if (User.Identity.IsAuthenticated && User.IsInRole("Reader"))
            {
                viewModel.ShowInfo = true;
                viewModel.UserReadings = _unitOfWork.ReadingRepo
                                .GetReadingsForUser(User.Identity.GetUserId())
                                    .ToLookup(r => r.MangaId);
            }
            return View(viewModel);
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

MangaHub/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MangaHub/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MangaHub/Views/Home/Index.cshtml
@model MangaHub.Core.ViewModels.MangasViewModel
@{
    ViewBag.Title = "Home Page";
}


<div class="container manga-list">
    <div class="row pb-4 backgroundWhite">
        @foreach (var manga in Model.Mangas)
        {
            <div class="manga-pane">
                <div class="row">
                    <div class="col-12 col-lg-4">
                        <div class="manga-title">
                            <a title="Detail" href="@Url.Action("Details","Mangas",new {id = manga.Id })">
                                <h2 class="text-warning">@manga.Title</h2>
                            </a>
                            @if (Model.ShowInfo)
                            {
                                <span class="manga-title-divider">|</span>
                                
                                var isReading = Model.UserReadings.Contains(manga.Id);
                                <a class="book" title="@(isReading? "Reading":"Read")">
                                    <i class="fa @(isReading? "fa-book-reader": "fa-book")"></i>
                                </a>
                            }
                        </div>
                        <div class="manga-picture">
                            @{
                                var imageSrc = string.Format("data:image/jpg;base64,{0}", Convert.ToBase64String(manga.Picture));
                            }
                            <img src=@imageSrc />
                        </div>
                        <h4>@manga.Genre.Name</h4>
                        <p>@manga.Description</p>
                    </div>
                    <div class="col-12 col-lg-8">
                        <div class="row">
                            <div class="col-12">
                                <h3 class="text-warning">by: @manga.Artist.Name</h3>
                                <h3 style="color: #bbb9b9">Uploaded: @manga.DateCreated.ToString("d MMM yyyy HH:mm")</h3>
                            </div>
                            <div class="col-12">
                                @if (manga.Chapters.Any())
                                {
                                    <table class="table table-striped manga-table">
                                        <thead>
                                            <tr>
                                                <th>Chapter No.</th>
                                                <th>Pages</th>
                                                <th>Information</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var chap in manga.Chapters)
                                            {
                                                <tr>
                                                    <td>@chap.ChapterNo</td>
                                                    <td>@chap.NumberOfPages</td>
                                                    <td>@chap.Information</td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    <div class="pagination-container">
                                        <nav>
                                            <ul class="pagination"></ul>
                                        </nav>
                                    </div>
                                    <div class="row_count"></div>
                                }
                                else
                                {
                                    <p>No Chapter exists...</p>
                                }
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        }

    </div>
</div>

@section scripts
{
    <script>
        $(document).ready(function () {
            applyPagination();
        });
    </script>

}